### ISSUE TITLE
Add other tripwire tools

### ISSUE THREAD

**Issue by maltfield** [remiflavien1/awesome-anti-forensic#4]
Thanks for adding BusKill in #3 :)

I realized that I have been tracking a bunch of other tools related in our BusKill docs, and all of them are great candidates for this `awesome-anti-forensic` list

 * https://docs.buskill.in/buskill-app/en/stable/attribution.html#similar-projects

1. [USB Kill](https://github.com/hephaest0s/usbkill)
2. [USB Death](https://github.com/trpt/usbdeath)
3. [Silk Guardian](https://github.com/NateBrune/silk-guardian)
4. [Day Tripper](https://github.com/dekuNukem/daytripper)
5. [USBGuard](https://usbguard.github.io/)
6. [suicideCrypt](https://github.com/MonolithInd/suicideCrypt)
7. [panic_bcast](https://github.com/qnrq/panic_bcast)
8. [Nuke My LUKS](https://github.com/juliocesarfort/nukemyluks)
9. [luksAddNuke](http://lxer.com/module/newswire/view/103692/index.html)
10. [cryptsetup-nuke-keys](https://gitlab.com/kalilinux/packages/cryptsetup-nuke-keys)
11. [TAILS Memory Erasure](https://tails.boum.org/contribute/design/memory_erasure/)
12. [TEDD (Transparent Emergency Data Destruction)](https://bitbucket.org/ausiv4/tedd/src/default/)
13. [s53](https://github.com/BrassHornCommunications/s53)
14. [swatd](https://github.com/defuse/swatd)
15. [Centry](https://github.com/0xPoly/Centry)
16. [xxUSBSentinel](https://github.com/thereisnotime/xxUSBSentinel)
17. [Ripple](https://guardianproject.info/apps/info.guardianproject.ripple/)

Would you be open to adding these and also grouping them in a distinct category of tools that are designed specifically to execute an emergency wipe after being triggered by some hardware tripwire? I'd call the new category `Emergency Tripwire Tools` or similar.

**Comment by shadawck** [comment]
Nice suggestions ! It's added mostly in the hardware section.
